### ISSUE TITLE
[BUG] Input Parameter (Variable) Does Not Support Multiple Values

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/run-runbook-action#167]
The input parameter, `variable` specifies a value for a prompted variable in the format, `Name:Value`. Currently, it does not support multiple values either through a delimited string or a multiline input. This issue proposes the creation of a new parameter, `variables` that would support this feature. The behaviour of `variable` would remain unchanged.

**Comment by johnsimons** [comment]
@jbristowe are u proposing something like:
```yaml
variables = {
   name1 = value1
   name2 = value2
}
```
so no magical delimiter 😄

**Comment by jbristowe** [comment]
We can implement support for multiline input in the YAML as follows:

```yaml
variables = |
  Name1:Value1
  Name2:Value2
```

Alternatively, we can support multiple variables using a delimiter:

```yaml
variables='Name1:Value1,Name2:Value2'
```

**Comment by johnsimons** [comment]
delimiters are hard to support, eg what happens when the value contains the delimiter character

**Comment by jbristowe** [comment]
We will support escape characters:

```yaml
'Name1:Value1,Name2:Value2'
# ['Name1:Value1', 'Name2:Value2']

'Name1:Value1,Name2:Value\,2'
# ['Name1:Value1', 'Name2:Value,2']
```
